In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("artists.csv")

In [6]:
df.head()

,id,name,followers,popularity,genres,main_genre
0,6YROFUbu5zRCHi2xkir5pk,Brian Hyland,67223,47,[],Pop
1,5tFRohaO5yEsuJxmMnlCO9,Barns Courtney,602647,62,[],Electronic
2,3oDbviiivRWhXwIE8hxkVV,The Beach Boys,5139194,76,['baroque pop'],Classical
3,60zvRmhQHRxokEB1taAVpN,Beth Malone,1569,29,['musicals'],Classical
4,4hxDvVq5t8ebPYPdBl1F9f,HELLYEAH,769490,52,"['groove metal', 'metal']",Rock

In [7]:
df.columns

Index(['id', 'name', 'followers', 'popularity', 'genres', 'main_genre'], dtype='object')

In [8]:
df.head(20)

,id,name,followers,popularity,genres,main_genre
0,6YROFUbu5zRCHi2xkir5pk,Brian Hyland,67223,47,[],Pop
1,5tFRohaO5yEsuJxmMnlCO9,Barns Courtney,602647,62,[],Electronic
2,3oDbviiivRWhXwIE8hxkVV,The Beach Boys,5139194,76,['baroque pop'],Classical
3,60zvRmhQHRxokEB1taAVpN,Beth Malone,1569,29,['musicals'],Classical
4,4hxDvVq5t8ebPYPdBl1F9f,HELLYEAH,769490,52,"['groove metal', 'metal']",Rock
5,2jwRHcdgkRhelYEMqndDKe,Yxngxr1,143628,45,[],Hip-Hop
6,07d5etnpjriczFBB8pxmRe,BJ The Chicago Kid,464821,59,[],Hip-Hop
7,50bY8HGxT0SuDgJX3AilTT,Sesame Street,138888,65,"[""children's music""]",Folk
8,3hyGGjxu73JuzBa757H6R5,The Mountain Goats,419856,57,"['folk punk', 'anti-folk', 'indie folk']",Folk
9,0KUfoAHP20vQHuDhiEAa8r,Cookie Monster,41911,56,"[""children's music""]",Folk
10,5ns1lY8egNoPsITbbNpli6,Clorofila,20782,16,"['mexican indie', 'latin alternative', 'electr...",Electronic
11,41x3tK4pmcp109A09rYtxj,Ram-Zet,4100,7,"['avant-garde', 'progressive metal', 'gothic m...",Rock
12,7EEiVZvj6RCEtVX2F2pyxu,Slim Jxmmi,117904,54,[],Hip-Hop
13,5i4JbHYkeCa702YXS68RGf,Catherine Zeta-Jones,25737,51,['musicals'],Classical
14,1zNqQNIdeOUZHb8zbZRFMX,Swae Lee,3146480,79,[],Hip-Hop
15,7If8DXZN7mlGdQkLE2FaMo,The Gaslight Anthem,362398,52,[],Rock
16,6cutt8thPFUICMfxaYerWd,MY FIRST STORY,718506,60,"['j-rock', 'j-pop', 'anime']",Pop
17,7iZtZyCzp3LItcw1wtPI3D,Rae Sremmurd,7811582,72,[],Hip-Hop
18,2TkSDFFCkyiMrHyL1a5BbF,Laura Osnes,16585,42,['musicals'],Classical
19,6pdcQa7by8IKuoVXvgknlI,Rilès,929303,63,['french rap'],Hip-Hop

In [9]:
df.dtypes

id            object
name          object
followers      int64
popularity     int64
genres        object
main_genre    object
dtype: object

In [10]:
df["name"] = df["name"].astype(str)

In [11]:
df["name"] = df["name"].str.lower()

In [12]:
df.dtypes

id            object
name          object
followers      int64
popularity     int64
genres        object
main_genre    object
dtype: object

In [13]:
print(df["name"])

0                brian hyland
1              barns courtney
2              the beach boys
3                 beth malone
4                    hellyeah
                 ...
63852             dropped out
63853                   k.tee
63854                rb stone
63855    sabotage soundsystem
63856                   lemay
Name: name, Length: 63857, dtype: object

In [14]:
df["genres"] = df["genres"].astype(str)
df["genres"] = (df["genres"].str.replace(r"[", "", regex = False )
              .str.replace(r"]", "", regex = False )
              .str.replace(r"'", "", regex = False ))

In [15]:
df["genres"].drop

<bound method Series.drop of 0
1
2                                              baroque pop
3                                                 musicals
4                                      groove metal, metal
                               ...
63852    desi hip hop, indian indie, hindi hip hop, hin...
63853                   jungle, drum and bass, liquid funk
63854                                    blues rock, blues
63855                                  reggae rock, reggae
63856                                             edm trap
Name: genres, Length: 63857, dtype: object>

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63857 entries, 0 to 63856
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          63857 non-null  object
 1   name        63857 non-null  object
 2   followers   63857 non-null  int64
 3   popularity  63857 non-null  int64
 4   genres      63857 non-null  object
 5   main_genre  63857 non-null  object
dtypes: int64(2), object(4)
memory usage: 2.9+ MB

In [17]:
df.head(10)

,id,name,followers,popularity,genres,main_genre
0,6YROFUbu5zRCHi2xkir5pk,brian hyland,67223,47,,Pop
1,5tFRohaO5yEsuJxmMnlCO9,barns courtney,602647,62,,Electronic
2,3oDbviiivRWhXwIE8hxkVV,the beach boys,5139194,76,baroque pop,Classical
3,60zvRmhQHRxokEB1taAVpN,beth malone,1569,29,musicals,Classical
4,4hxDvVq5t8ebPYPdBl1F9f,hellyeah,769490,52,"groove metal, metal",Rock
5,2jwRHcdgkRhelYEMqndDKe,yxngxr1,143628,45,,Hip-Hop
6,07d5etnpjriczFBB8pxmRe,bj the chicago kid,464821,59,,Hip-Hop
7,50bY8HGxT0SuDgJX3AilTT,sesame street,138888,65,"""childrens music""",Folk
8,3hyGGjxu73JuzBa757H6R5,the mountain goats,419856,57,"folk punk, anti-folk, indie folk",Folk
9,0KUfoAHP20vQHuDhiEAa8r,cookie monster,41911,56,"""childrens music""",Folk

In [18]:
df = df.drop("genres", axis=1)

In [19]:
df["main_genre"] = df["main_genre"].str.lower()
df = df.rename(columns = {"main_genre": "genre"})

In [20]:
df.to_csv("artists1.csv", index=False)

In [17]:
df.head(50)

,id,name,followers,popularity,genre
0,6YROFUbu5zRCHi2xkir5pk,brian hyland,67223,47,pop
1,5tFRohaO5yEsuJxmMnlCO9,barns courtney,602647,62,electronic
2,3oDbviiivRWhXwIE8hxkVV,the beach boys,5139194,76,classical
3,60zvRmhQHRxokEB1taAVpN,beth malone,1569,29,classical
4,4hxDvVq5t8ebPYPdBl1F9f,hellyeah,769490,52,rock
5,2jwRHcdgkRhelYEMqndDKe,yxngxr1,143628,45,hip-hop
6,07d5etnpjriczFBB8pxmRe,bj the chicago kid,464821,59,hip-hop
7,50bY8HGxT0SuDgJX3AilTT,sesame street,138888,65,folk
8,3hyGGjxu73JuzBa757H6R5,the mountain goats,419856,57,folk
9,0KUfoAHP20vQHuDhiEAa8r,cookie monster,41911,56,folk
10,5ns1lY8egNoPsITbbNpli6,clorofila,20782,16,electronic
11,41x3tK4pmcp109A09rYtxj,ram-zet,4100,7,rock
12,7EEiVZvj6RCEtVX2F2pyxu,slim jxmmi,117904,54,hip-hop
13,5i4JbHYkeCa702YXS68RGf,catherine zeta-jones,25737,51,classical
14,1zNqQNIdeOUZHb8zbZRFMX,swae lee,3146480,79,hip-hop
15,7If8DXZN7mlGdQkLE2FaMo,the gaslight anthem,362398,52,rock
16,6cutt8thPFUICMfxaYerWd,my first story,718506,60,pop
17,7iZtZyCzp3LItcw1wtPI3D,rae sremmurd,7811582,72,hip-hop
18,2TkSDFFCkyiMrHyL1a5BbF,laura osnes,16585,42,classical
19,6pdcQa7by8IKuoVXvgknlI,rilès,929303,63,hip-hop
20,3bW9aRkzZhlE53ca3djW8Z,jeanine tesori,1658,35,classical
21,498OLUGBV0hSPmRHokzvaA,alexander hanson,687,41,classical
22,0CKa42Jqrc9fSFbDjePaXP,big k.r.i.t.,950632,58,hip-hop
23,1cHFz6lrt7KAsBV8j2Ny1g,the blues brothers,448981,56,blues
24,47mxBSV8e4ssFImQjxzePn,suis la lune,29185,32,rock
25,3rpd8ePtYWGXq5te4laEwY,harriet harris,270,24,classical
26,7iHXhGerkdpvUAIb67GCSj,diana panton,21816,39,jazz
27,0oE1QxknblYdWQt51QjyrG,michael cerveris,2755,31,classical
28,4YAN46l70QV0PGXlMg0iHi,dillinger four,36619,35,rock
29,27R1aBy7FfkYevfYen4sMp,george birge,75043,54,country
30,0k9kVbqy5B8J1jbQm4XcMA,roberta colindrez,91,12,classical
31,1vrC8QDkFBw7mkWShqEcXZ,lisa kron,135,31,classical
32,743OB85I8BftMRfuNAO1RS,ann harada,1053,35,classical
33,4NgfOZCL9Ml67xzM0xzIvC,janis joplin,3604137,62,rock
34,7tHd518aPjJYUgyv9bidBz,judy kuhn,37426,55,classical
35,7arQA31aZVS8yS6zUveWzb,cj,282841,62,hip-hop
36,3FCu4XKU7SMobrCqEnTRSJ,little apple band,6963,33,folk
37,5rX1EodZfwxmW4fQX2Caot,jonny lang,265349,48,blues
38,4QGKWF55nqfGYToZkoZPRF,one morning left,38169,34,rock
39,1fZpYWNWdL5Z3wrDtISFUH,shakey graves,594751,58,folk
40,51Blml2LZPmy7TTiAg47vQ,u2,13715623,78,rock
41,3UUl93ABT7zywawX0QA7MC,breadwinner,5014,16,rock
42,4pFb5Ycz7oHBhVS623cMdf,emily skeggs,666,23,classical
43,1PoFNQQDFXvOYm6Dx8coAa,esmé patterson,28777,23,country
44,2NC0NvcP3iJvpCPepplwof,sydney lucas,326,26,classical
45,6RvruFAgvsAb4B82u8wsSH,envy on the coast,37014,31,rock
46,3Q6OOkfssqoMSTtl11J5Uk,love,273598,46,rock
47,55CXG5KDJpRYwBopfYAJHa,jorma kaukonen,34539,35,blues
48,4TbtUt49IMXEIMmNdifHb1,stephen sondheim,93717,51,classical
49,4PLsMEk2DCRVlVL2a9aZAv,soak,88596,42,folk