In [2]:
import pandas as pd
import numpy as np

In [3]:
df_song = pd.read_csv("songs.csv")
df_song.head()

,id,name,album_name,artists,danceability,energy,key,loudness,mode,speechiness,...,tempo,duration_ms,lyrics,year,genre,popularity,total_artist_followers,avg_artist_popularity,artist_ids,niche_genres
0,2ASl4wirkeYm3OWZxXKYuq,!!,Childhood Dreams,"[""Yxngxr1""]",0.788,0.648,7,-9.135,0,0.3150,...,79.998,114000,"Fuck the bitch, now she running with my kids\n...",2019,Hip-Hop,29,143628,45.0,"[""2jwRHcdgkRhelYEMqndDKe""]",[]
1,5tA3ImW310llKo8EMBj2Ga,!!Noble Stabbings!!,Situationist Comedy,"[""Dillinger Four""]",0.171,0.957,2,-5.749,1,0.1490,...,175.317,197400,You like to stand on the other side\nPoint and...,2002,Rock,0,36619,35.0,"[""4YAN46l70QV0PGXlMg0iHi""]","[""melodic hardcore"", ""pop punk"", ""punk"", ""skat..."
2,0fROT4kK5oTm8xO8PX6EJF,!I'll Be Back!,!I'll Be Back!,"[""Ril\u00e8s""]",0.823,0.612,1,-7.767,1,0.2480,...,142.959,178533,"It's been a while, shit, I missed the rehab, p...",2018,Hip-Hop,43,929303,63.0,"[""6pdcQa7by8IKuoVXvgknlI""]","[""french rap""]"
3,1xBFhv5faebv3mmwxx7DnS,!Lost!,!Lost!,"[""Ril\u00e8s""]",0.729,0.552,7,-8.562,0,0.0650,...,86.103,186197,I would like to give you all my time\nI would ...,2018,Hip-Hop,0,929303,63.0,"[""6pdcQa7by8IKuoVXvgknlI""]","[""french rap""]"
4,1SCFa6gt3r6juLsIqpdwY3,!liaF cipE,The Bree-TeenZ,"[""One Morning Left""]",0.483,0.894,9,-4.164,1,0.0546,...,140.058,200200,They scream when I'm walking in the street\nEv...,2011,Rock,0,38169,34.0,"[""4QGKWF55nqfGYToZkoZPRF""]","[""metalcore"", ""post-hardcore""]"

In [4]:
df_song.columns

Index(['id', 'name', 'album_name', 'artists', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'duration_ms', 'lyrics', 'year',
       'genre', 'popularity', 'total_artist_followers',
       'avg_artist_popularity', 'artist_ids', 'niche_genres'],
      dtype='object')

In [5]:
df_song = df_song.drop(
    ['danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'duration_ms', 'lyrics', 'year', 'popularity', 'total_artist_followers',
       'avg_artist_popularity', 'niche_genres'],
    axis=1
)

In [6]:
df_song.head()

,id,name,album_name,artists,genre,artist_ids
0,2ASl4wirkeYm3OWZxXKYuq,!!,Childhood Dreams,"[""Yxngxr1""]",Hip-Hop,"[""2jwRHcdgkRhelYEMqndDKe""]"
1,5tA3ImW310llKo8EMBj2Ga,!!Noble Stabbings!!,Situationist Comedy,"[""Dillinger Four""]",Rock,"[""4YAN46l70QV0PGXlMg0iHi""]"
2,0fROT4kK5oTm8xO8PX6EJF,!I'll Be Back!,!I'll Be Back!,"[""Ril\u00e8s""]",Hip-Hop,"[""6pdcQa7by8IKuoVXvgknlI""]"
3,1xBFhv5faebv3mmwxx7DnS,!Lost!,!Lost!,"[""Ril\u00e8s""]",Hip-Hop,"[""6pdcQa7by8IKuoVXvgknlI""]"
4,1SCFa6gt3r6juLsIqpdwY3,!liaF cipE,The Bree-TeenZ,"[""One Morning Left""]",Rock,"[""4QGKWF55nqfGYToZkoZPRF""]"

In [7]:
df_song["name"] = df_song["name"].astype(str)
df_song["name"] = df_song["name"].str.replace(r'[!"]|\.','',regex=True)

In [8]:
df_song["name"] = df_song["name"].str.lower()

In [9]:
df_song["album_name"] = df_song["album_name"].astype(str)
df_song["album_name"] = (df_song["album_name"]
                        .str.replace(r"+", "", regex = False)
                        .str.replace(r"'", "", regex = False)
                        .str.replace(r".", "", regex = False)
                        .str.replace(r'"', '', regex = False)
                        .str.replace(r'!', '', regex = False))
df_song["album_name"] = df_song["album_name"].str.lower()

In [10]:
df_song["artists"] = df_song["artists"].astype(str)
df_song["artists"] = df_song["artists"].str.replace(r'[\[\]"]', '', regex=True)
df_song["artists"]

0                            Yxngxr1
1                     Dillinger Four
2                         Ril\u00e8s
3                         Ril\u00e8s
4                   One Morning Left
                     ...
491627                          None
491628                          None
491629                     Pronobozo
491630    Sugar Ray, Rosie O'Donnell
491631    Macy Gray, Rosie O'Donnell
Name: artists, Length: 491632, dtype: object

In [11]:
df_song["artist_ids"] = df_song["artist_ids"].astype(str)
df_song["artist_ids"] = df_song["artist_ids"].str.replace(r'[\[\]"]', '', regex=True)
df_song["artist_ids"]

0                                 2jwRHcdgkRhelYEMqndDKe
1                                 4YAN46l70QV0PGXlMg0iHi
2                                 6pdcQa7by8IKuoVXvgknlI
3                                 6pdcQa7by8IKuoVXvgknlI
4                                 4QGKWF55nqfGYToZkoZPRF
                               ...
491627                            2ZO5sFPyILDQkFdS4HJPFS
491628                            2ZO5sFPyILDQkFdS4HJPFS
491629                            4e0ETTbxMHwq7DtH9LSHAJ
491630    4uN3DsfENc7dp0OLO0FEIb, 4V8U8U6LwsHGyRTLCt9t19
491631    4ylR3zwA0zaapAu94fktwa, 4V8U8U6LwsHGyRTLCt9t19
Name: artist_ids, Length: 491632, dtype: object

In [12]:
df_song = df_song[
    df_song["name"].notna() &
    (df_song["name"].str.strip() != "") & (df_song["name"].str.strip() != " ")
]

In [13]:
df_song["artists"] = df_song["artists"].str.lower()

In [14]:
df_song["genre"] = df_song["genre"].str.lower()

In [15]:
df_song = df_song.drop_duplicates(subset=["name"], keep="first")

In [16]:
df_song = df_song.dropna(subset=["name"])

In [17]:
df_song.info()

<class 'pandas.core.frame.DataFrame'>
Index: 303138 entries, 1 to 491628
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          303138 non-null  object
 1   name        303138 non-null  object
 2   album_name  303138 non-null  object
 3   artists     303138 non-null  object
 4   genre       303138 non-null  object
 5   artist_ids  303138 non-null  object
dtypes: object(6)
memory usage: 16.2+ MB

In [18]:
df_song.head(80)

,id,name,album_name,artists,genre,artist_ids
1,5tA3ImW310llKo8EMBj2Ga,noble stabbings,situationist comedy,dillinger four,rock,4YAN46l70QV0PGXlMg0iHi
2,0fROT4kK5oTm8xO8PX6EJF,i'll be back,ill be back,ril\u00e8s,hip-hop,6pdcQa7by8IKuoVXvgknlI
3,1xBFhv5faebv3mmwxx7DnS,lost,lost,ril\u00e8s,hip-hop,6pdcQa7by8IKuoVXvgknlI
4,1SCFa6gt3r6juLsIqpdwY3,liaf cipe,the bree-teenz,one morning left,rock,4QGKWF55nqfGYToZkoZPRF
6,5PIf0fmKJzgK8jgyqXaHGZ,rip,escape,ram-zet,rock,41x3tK4pmcp109A09rYtxj
...,...,...,...,...,...,...
87,1ReFo3JhwYbk1XOlOQu3ka,ole baugh road,southern star,alabama,country,6rJqqRce0Kvo2dJUXoHleC
89,48L3vBFHcylQf2nZ8SQ2rz,p is still free,return of the boom bap,krs-one,hip-hop,2gINJ8xw86xawPyGvx1bla
90,10lNLjUExk8lUin4pYkQKQ,"panis angelicus, cff 209",100 christmas masterworks,"pl\u00e1cido domingo, orchestra sinfonica di m...",classical,"4pU3BpenOZFEBzORx2YBJW, 5skyG64028a3FaeFYvT3mE..."
91,3xMuMLXbvbv6LSQaJlkyOh,"please miss giry, i want to go back",love never dies,andrew lloyd webber,pop,4aP1lp10BRYZO658B2NwkG
92,4wOdBrX82HqN6lxc50BD9r,president dead,holy wood,marilyn manson,rock,2VYQTNDsvvKN9wmU5W7xpj

In [19]:
print(df_song.columns)

Index(['id', 'name', 'album_name', 'artists', 'genre', 'artist_ids'], dtype='object')

In [21]:
df_song.to_csv("songs1.csv", index=False)